---
label: Project
hide_body: false
fields:
- name: heading
  type: text
  config:
    required: true
  label: Heading
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
pages:
- content/projects/project_x1.md
