---
label: Project
hide_body: false
fields:
- name: heading
  type: text
  config:
    required: true
  label: Heading
- name: blocks
  type: blocks
  label: blocks
  template_types: []
  config:
    min: 
    max: 
